#Attention!! tabulation (4 espaces) et encodage

oc_platform_home:
    path:      /{page}
    defaults:  { _controller: OCPlatformBundle:Advert:index, page: 1 }
    requirements:
        page: \d*

oc_platform_view:
    path:      /advert/{id}
    defaults:  { _controller: OCPlatformBundle:Advert:view }
    requirements:
        id: \d+

oc_platform_add:
    path:      /add
    defaults:  { _controller: OCPlatformBundle:Advert:add }

oc_platform_edit:
    path:      /edit/{id}
    defaults:  { _controller: OCPlatformBundle:Advert:edit }
    requirements:
        id: \d+

oc_platform_delete:
    path:      /delete/{id}
    defaults:  { _controller: OCPlatformBundle:Advert:delete }
    requirements:
        id: \d+

# oc_platform_home:
#     path:      /
#     defaults:  { _controller: OCPlatformBundle:Advert:index }

# oc_platform_view:
#     path:      /advert/{id}
#     defaults:  { _controller: OCPlatformBundle:Advert:view }

# oc_platform_view_slug:
#     path:      /{year}/{slug}.{_format}
#     defaults:  { _controller: OCPlatformBundle:Advert:viewSlug, _format: html}
#     requirements:
#         year:   \d{4}
#         format: html|xml

# oc_platform_add:
#     path:      /add
#     defaults:  { _controller: OCPlatformBundle:Advert:add }

########### paramètres système #######################################################


########### Le paramètre {_format} 

# Lorsqu'il est utilisé (comme notre paramètre {format}, ajoutez juste un underscore), 
# alors un header avec le Content-type correspondant est ajouté à la réponse retournée.
# Exemple : vous appelez /platform/2014/webmaster.xml et le Kernel sait que la réponse 
# retournée par le contrôleur est du XML, grâce au paramètre "_format" contenu dans la route.
# Ainsi, avant d'envoyer la réponse à notre navigateur, le header Content-type: application/xml sera ajouté.

########### Le paramètre {_locale}  

# Lorsqu'il est utilisé, il va définir la langue dans laquelle l'utilisateur
# souhaite obtenir la page. Ainsi, si vous avez défini des fichiers de traduction 
# ou si vous employez des bundles qui en utilisent, alors les traductions dans la 
# langue du paramètre {_locale} seront chargées. Pensez à mettre un requirements: 
# sur la valeur de ce paramètre pour éviter que vos utilisateurs ne demandent le russe
# alors que votre site n'est que bilingue français-anglais.

########### Le paramètre {_controller}  

# Eh oui, cette valeur que nous avons toujours mise dans le tableau defaults n'est rien
# d'autre qu'un paramètre de route ! Evidemment, c'est un paramètre que nous ne mettons
# jamais dans le path de nos routes, mais je tenais à vous montrer qu'il n'est pas
# différent des autres. Le tableau defaults correspond juste aux valeurs par défaut 
# de nos paramètres, qu'ils soient ou non présent dans le path  de la route.

#######################################################################################